name: zapstorm

services:
  # Banco de dados MongoDB
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=zapstorm

  # Serviço de mensageria RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  # Servidor API principal
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/zapstorm
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - JWT_SECRET=mysupersecretkey
      - EVOLUTION_API_URL=http://evo.prado-cafe.com
      - EVOLUTION_API_TOKEN=cdc87090-5f5f-4f90-bc7d-508257953bc3

  # Worker de processamento de mensagens
  message-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
      - api
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/zapstorm
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - EVOLUTION_API_URL=http://evo.prado-cafe.com
      - EVOLUTION_API_TOKEN=cdc87090-5f5f-4f90-bc7d-508257953bc3
    command: ["npm", "run", "worker:messages"]

  # Worker de agendamento
  scheduler-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
      - api
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/zapstorm
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - EVOLUTION_API_URL=http://evo.prado-cafe.com
      - EVOLUTION_API_TOKEN=cdc87090-5f5f-4f90-bc7d-508257953bc3
    command: ["npm", "run", "worker:scheduler"]

  # Worker de alertas
  alert-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
      - api
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/zapstorm
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - EVOLUTION_API_URL=http://evo.prado-cafe.com
      - EVOLUTION_API_TOKEN=cdc87090-5f5f-4f90-bc7d-508257953bc3
    command: ["npm", "run", "worker:alerts"]

  # Worker de webhooks
  webhook-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    depends_on:
      - mongodb
      - rabbitmq
      - api
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/zapstorm
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672
      - EVOLUTION_API_URL=http://evo.prado-cafe.com
      - EVOLUTION_API_TOKEN=cdc87090-5f5f-4f90-bc7d-508257953bc3
    command: ["npm", "run", "worker:webhooks"]

  # Frontend da aplicação
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:3001/api

volumes:
  mongodb_data:
  rabbitmq_data: 